Fixed
> operiva@0.0.0 build
> tsc -b && vite build

src/components/pyramid/categoryMapping.ts:76:29 - error TS2591: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @ty
pes/node` and then add 'node' to the types field in your tsconfig.
76   const { pyramidLayers } = require('./pyramidData');
                               ~~~~~~~

Found 1 error.